code

;all c library function
;/////////////////////////////////////////////////////////





def ___assert___ 10         ;assert.h
def ___isalnum___           ;ctype.h
def ___isalpha___
def ___iscntrl___
def ___isdigit___
def ___isgraph___
def ___islower___
def ___isprint___
def ___ispunct___
def ___isspace___
def ___isupper___
def ___isxdigit___
def ___tolower___
def ___toupper___
def ___acos___              ;math.h
def ___asin___
def ___atan___
def ___atan2___
def ___ceil___
def ___cos___
def ___cosh___
def ___exp___
def ___fabs___
def ___floor___
def ___fmod___
def ___frexp___
def ___labs___
def ___ldexp___
def ___log___
def ___log10___
def ___modf___
def ___pow___
def ___sin___
def ___sinh___
def ___sqrt___
def ___tan___
def ___tanh___
def ___isfinite___
def ___isnormal___
def ___isnan___
def ___isinf___
def Math_Vector3_Normalize
def Math_Vector3_Length
def Math_Vector3_RotateX
def Math_Vector3_RotateY
def Math_Vector3_RotateZ
def Math_Vector3_BoundPointSphere
def Math_Vector3_ApplyProjection
def Math_Quaternion_SetEuler
def Math_Matrix3_Identity
def Math_Matrix3_GetNormalMatrix
def Math_Matrix4_Identity
def Math_Matrix4_MakePerspective
def Math_Matrix4_MakeOrthographic
def Math_Matrix4_MakeFrustum
def Math_Matrix4_MakeLookAt
def Math_Matrix4_Multiply
def Math_Matrix4_Compose
def Math_Matrix4_GetRotationQuaternion
def Math_Matrix4_GetInverse
def Math_Matrix4_MultiplyVector3
def Math_Matrix4_MultiplyVector4
def Math_Matrix4_Translate
def Math_Matrix4_DirToMatrix
def Math_Matrix4_RotateX
def Math_Matrix4_RotateY
def Math_Matrix4_RotateZ
def Math_RayCaster_Intersect
def Math_RayCaster_IntersectForIndex
def ___raise___             ;signal.h
def ___clearerr___          ;stdio.h
def ___fclose___
def ___feof___
def ___ferror___
def ___fflush___
def ___fgetc___
def ___fgetpos___
def ___fgets___
def ___fopen___
def ___fprintf___
def ___fputc___
def ___fputs___
def ___fread___
def ___freopen___
def ___fscanf___
def ___fseek___
def ___fsetpos___
def ___ftell___
def ___fwrite___
def ___getc___
def ___getchar___
def ___gets___
def ___perror___
def ___printf___
def ___putc___
def ___putchar___
def ___puts___
def ___remove___
def ___rename___
def ___rewind___
def ___scanf___
def ___setbuf___
def ___setvbuf___
def ___sprintf___
def ___sscanf___
def ___tmpfile___
def ___tmpnam___
def ___ungetc___
def ___vprintf___
def ___vfprintf___
def ___vsprintf___
def ___calloc___            ;stdlib.h
def ___free___
def ___malloc___
def ___realloc___
def ___abs___
def ___div___
def ___ldiv___
def ___atof___
def ___atoi___
def ___atol___
def ___abort___
def ___atexit___
def ___bsearch___
def ___exit___
def ___getenv___
def ___qsort___
def ___rand___
def ___srand___
def ___system___
def ___strtof___
def ___longjmp___           ;setjmp.h
def ___setjmp___
def ___memchr___            ;string.h
def ___memcmp___
def ___memcpy___
def ___memmove___
def ___memset___
def ___strcat___
def ___strchr___
def ___strcmp___
def ___strcoll___
def ___strcpy___
def ___strcspn___
def ___strerror___
def ___strlen___
def ___strncat___
def ___strncmp___
def ___strncpy___
def ___strpbrk___
def ___strrchr___
def ___strspn___
def ___strstr___
def ___strtod___
def ___strtok___
def ___strtol___
def ___strtoul___
def ___strxfrm___
def ___strncasecmp___
def ___asctime___           ;time.h
def ___clock___
def ___ctime___
def ___difftime___
def ___gmtime___
def ___localtime___
def ___mktime___
def ___strftime___
def ___time___
def GUI_Windows_Create                          ;ui.h
def GUI_Lable_Create
def GUI_Button_Create
def GUI_IconButton_Create
def GUI_Image_Create
def GUI_PanelElement_Create
def GUI_PanelTransformElement_Create
def GUI_Canvas_Create
def GUI_TextBox_Create
def GUI_ScrollPanel_Create
def GUI_SubScrollPanel_Create
def GUI_3DCanvas_Create
def GUI_TextView_Create
def GUI_ListView_Create
def GUI_EditBox_Create
def GUI_ProgressBar_Create
def GUI_Animation_Create
def GUI_DataView_Create
def GUI_Element_AddElement
def GUI_Element_RemoveElement
def GUI_Element_SetText
def GUI_Element_GetText
def GUI_Element_Clear
def GUI_Element_AddText
def GUI_Element_SetFontInfo
def GUI_Element_SetFontColor
def GUI_IconButton_SetIcon
def GUI_IconButton_SetIconFile
def GUI_IconButton_SetIconIndex
def GUI_Element_SetImage
def GUI_Image_SetImage
def GUI_Canvas_SetRenderItems
def GUI_Element_SetUIEventCallBack
def GUI_Button_SetButtonChecked
def GUI_TextBox_SetFile
def GUI_ScrollPanel_SetItemData
def GUI_SubScrollPanel_SetDataStruct
def GUI_TextView_SetClearTime
def GUI_ListView_SetCell
def GUI_ListView_SetHeaderInfo
def GUI_ListView_SetCellInfoText
def GUI_ListView_SetCellInfoInteger
def GUI_ListView_SetCellInfoFloat
def GUI_ListView_SetCellInfoImage
def GUI_ListView_SetItemHeight
def GUI_ListView_AddNewRow
def GUI_ListView_ClearCell
def GUI_ListView_GetCellCount
def GUI_ListView_DeleteRow
def GUI_Element_SetVisible
def GUI_Element_SetUserData0
def GUI_Element_SetUserData1
def GUI_Element_SetUserData2
def GUI_Element_SetUserData3
def GUI_Element_GetUserData0
def GUI_Element_GetUserData1
def GUI_Element_GetUserData2
def GUI_Element_GetUserData3
def GUI_Element_SetTextureCoordsInfo
def GUI_Element_SetTextureCoordsInfo1
def GUI_Element_SetTexture
def GUI_Element_SetTextureHandle
def GUI_Element_UpdateTextureCoordsInfo
def GUI_Element_SetPos
def GUI_Element_SetBound
def GUI_Button_SetCheckMode
def GUI_Button_GetChecked
def GUI_ProgressBar_SetRange
def GUI_ProgressBar_SetPos
def GUI_Button_SetEnable
def GUI_ListView_VisibleLastRow
def GUI_Element_SetTextAlign
def GUI_ListView_SetSelect
def GUI_SetShadowHandle
def GUI_GetShadowHandle
def GUI_Animation_SetAnimationInfo
def GUI_Animation_Reset
def GUI_Element_SetColor
def GUI_ListView_GetSelect
def GUI_Element_BringToFront
def GUI_Element_SendToBack
def GUI_ListView_SetItemData
def GUI_ListView_GetItemData
def GUI_DataView_SetData
def GUI_TextBox_VisibleLastRow
def GUI_Element_GetChildForID
def GUI_Element_GetParent
def GUI_Element_GetPos
def GUI_Element_GetBound
def GUI_Element_SetZOrder
def GUI_RichTextView_Create
def GUI_Element_Release
def GUI_HtmlView_Create
def GUI_Element_SetID
def GUI_Element_GetID
def GUI_Element_SetReadOnly
def GUI_ListView_GetCellInfo
def Renderer_VertexBuffer_Create            ;render.h
def Renderer_VertexBuffer_Rlease
def Renderer_VertexBuffer_Update
def Renderer_VertexBuffer_Render0
def Renderer_VertexBuffer_Render1
def Renderer_IndexBuffer_Create
def Renderer_IndexBuffer_Rlease
def Renderer_IndexBuffer_Update
;def Renderer_VertexDataBuffer_Create
;def Renderer_VertexDataBuffer_Release
;def Renderer_VertexDataBuffer_Begin
;def Renderer_VertexDataBuffer_End
;def Renderer_VertexDataBuffer_Render
;def Renderer_VertexDataBuffer_Render_Index
def Renderer_BeginRenderTarget 288
def Renderer_EndRenderTarget
def Renderer_SetClearColor
def Renderer_SetDepthTest
def Renderer_SetDepthWrite
def Renderer_Clear
def Renderer_SetLineMode
def Renderer_SetMaterialFaces
def Renderer_SetBlending
def Renderer_Font_Render
def Renderer_Font_GetTextureInfo
def Renderer_Font_GetCharData
def Renerer_Font_BufferPrint
def Render_Font_GetTextInfo
def Render_Font_CreateFont
def Render_Font_ReleaseFont
def Render_Font_CalcAlignOffset
def Texture_Create_Target                   ;texture.h
def Texture_Create_File
def Texture_Create_Buffer
def Texture_CreateTextureFormStream
def Texture_Create_Pack
def Texture_Release
def Texture_Update_Buffer
def Texture_SetParame
def Material_Create                         ;material.h
def Material_Release
def Material_Begin
def Material_End
def Material_GetUniform
def Material_SetInt
def Material_SetFloat
def Material_SetVec2
def Material_SetVec3
def Material_SetVec4
def Material_SetMatrix3
def Material_SetMatrix4
def Material_SetMatrix4_1
def Material_SetTexture
def Material_SetVec2_1
def Material_SetVec3_1
def Material_SetVec4_1
def XMLDocument_Open                     ;xml.h
def XMLDocument_GetFirstNode
def XMLDocument_GetNode
def XMLDocument_Destroy
def XMLNode_GetFirstNode
def XMLNode_GetNextNode
def XMLNode_GetNode
def XMLNode_GetNodeCount
def XMLNode_GetChildCount
def XMLNode_GetName
def XMLNode_GetValue
def XMLNode_GetAttributeValue
def Sound_Play                              ;sound.h
def Sound_PlayOgg
def Sound_PlayByStream
def Sound_PlayDynamic
def Sound_Stop
def Sound_Pause
def Sound_Length
def Sound_GetPos
def Sound_SetPos
def Sound_GetVolume
def Sound_SetVolume
def Sound_GetAllVolume
def Sound_SetAllVolume
def Sound_StopAll
def Sound_UpdateSoundBuffer
def Sound_Mp3Decode
def Sound_GetBuffData
def Sound_GetState
def MPEG_CreateWithFileData
def MPEG_CreateWithDynamicData
def MPEG_CreateWithStream
def MPEG_GetInfo
def MPEG_Destroy
def MPEG_Decode
def MPEG_Ended
def MPEG_GetTime
def GetAssetFileSize                ;tools
def GetAssetFileData
def GetFileImageData
def SaveImageFile
def APP_GetAllCount
def APP_GetInfo
def APP_Startup
def APP_GetMemoryInfo
def APP_GetCPUInfo
def SYSTEM_GetFarData
def Format
def LogInfo
def LogOut
def LogMem
def HttpRequest
def GetFileList
def MakeMD532
def MakeMD516
def ConvertUTF8ToGB2312
def ConvertGB2312ToUTF8
def UnCompressData
def SYSTEM_SetFarData
def GetRemoteFile
def __nw__FUi                           ;new.h
def _main
def __dl__FPv
def __pure_virtual_called
def __vec_new
def __vec_delete

